spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test-security?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver