spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_security?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  mustache:
    servlet:
      expose-request-attributes: true

server:
  servlet:
    session:
      timeout: 90m